version: 2.1
notify:
  webhooks:
    - url: https://hermes.data.security.rackspace.com/circle
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
