version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.1

# Pipeline parameters
parameters:
  # These pipeline parameters are required by the "trigger-integration-tests-workflow"
  # job, by default.
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"


workflows:
  lint_pack-validate_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/shellcheck:
          exclude: "SC1009,SC1073"
      - orb-tools/pack
      - orb-tools/publish-dev:
          orb-name: rackerlabs/rsspca
          requires: [orb-tools/pack]

      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          requires: [orb-tools/publish-dev]


  integration-tests_prod-release:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      # - integration-tests-for-your-orb

      # publish a semver version of the orb. relies on
      # the commit subject containing the text "[semver:patch|minor|major|skip]"
      # as that will determine whether a patch, minor or major
      # version will be published or if publishing should
      # be skipped.
      # e.g. [semver:patch] will cause a patch version to be published.
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: rackerlabs/rsspca
          add-pr-comment: true
          publish-version-tag: true
          bot-user: racker-autobot
          fail-if-semver-not-indicated: false
          ssh-fingerprints: "5c:13:24:90:7e:0f:c9:d5:f7:16:55:3e:86:d9:5b:64"
#          requires:
#            - integration-tests-for-your-orb
          filters:
            branches:
              only: master
