parameters:
  docker_tag:
    default: "3.6"
    type: string
  working_directory:
    default: ~/src
    type: string
working_directory: << parameters.working_directory >>
docker:
  - image: circleci/python:<< parameters.docker_tag >>
